"""Audit actions and outcomes."""

from enum import StrEnum


class AuditAction(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGIN_LOCKED = "LOGIN_LOCKED"
    LOGOUT = "LOGOUT"
    OPERATOR_SELECTED = "OPERATOR_SELECTED"
    PASSWORD_RESET = "PASSWORD_RESET"
    BOOTSTRAP_ADMIN = "BOOTSTRAP_ADMIN"
    IMPORT_FILE_UPLOADED = "IMPORT_FILE_UPLOADED"
    IMPORT_MAPPING_UPDATED = "IMPORT_MAPPING_UPDATED"
    IMPORT_PREVIEW_CREATED = "IMPORT_PREVIEW_CREATED"
    IMPORT_PREVIEW_REGENERATED = "IMPORT_PREVIEW_REGENERATED"
    IMPORT_CONFIRM_REQUESTED = "IMPORT_CONFIRM_REQUESTED"
    IMPORT_CONFIRMED = "IMPORT_CONFIRMED"
    IMPORT_PREVIEW_STALE = "IMPORT_PREVIEW_STALE"
    IMPORT_COMPLETED = "IMPORT_COMPLETED"
    IMPORT_FAILED = "IMPORT_FAILED"
    IMPORT_CANCELLED = "IMPORT_CANCELLED"
    IMPORT_BATCH_CREATED = "IMPORT_BATCH_CREATED"
    IMPORT_BATCH_PREVIEW_CREATED = "IMPORT_BATCH_PREVIEW_CREATED"
    IMPORT_BATCH_CONFIRM_REQUESTED = "IMPORT_BATCH_CONFIRM_REQUESTED"
    IMPORT_BATCH_COMPLETED = "IMPORT_BATCH_COMPLETED"
    IMPORT_BATCH_FAILED = "IMPORT_BATCH_FAILED"
    IMPORT_BATCH_RETRIED = "IMPORT_BATCH_RETRIED"
    IMPORT_BATCH_CANCELLED = "IMPORT_BATCH_CANCELLED"
    IMPORT_FILE_REPLACED = "IMPORT_FILE_REPLACED"
    IMPORT_FILE_EXCLUDED = "IMPORT_FILE_EXCLUDED"
    IMPORT_FILE_RETRIED = "IMPORT_FILE_RETRIED"
    IMPORT_FILE_MAPPING_UPDATED = "IMPORT_FILE_MAPPING_UPDATED"
    IMPORT_FILE_SOURCE_ACQUIRED_AT_UPDATED = "IMPORT_FILE_SOURCE_ACQUIRED_AT_UPDATED"
    COLLECTION_SCREENING_RULES_UPDATED = "COLLECTION_SCREENING_RULES_UPDATED"


class AuditResult(StrEnum):
    SUCCESS = "success"
    FAILED = "failed"
    DENIED = "denied"
